//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1С_Франчайзи_Вятка
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSetITS
    {
        public int Id { get; set; }
        public int IdAgent { get; set; }
        public int IdClient { get; set; }
        public int IdIts { get; set; }
        public int Amount { get; set; }
        public int TotalPrice { get; set; }
    
        public virtual AgentSet AgentSet { get; set; }
        public virtual ClientSet ClientSet { get; set; }
        public virtual ItsSet ItsSet { get; set; }
    }
}
